<?php

namespace = App\Lib\Utils;

class FieldnameLookup
{
    private $fields = [
        ‘child_qualities_empathetic’ => 'Empathetic',
        ‘child_qualities_curious’ => 'Curious',
        ‘child_qualities_kind’ => 'Kind',
        ‘child_qualities_positive’ => 'Positive attitude',
        ‘child_qualities_cheerful’ => 'Cheerful',
        ‘child_qualities_hard_working’ => 'Hard-working',
        ‘child_qualities_resilient’ => 'Resilient',
        ‘child_qualities_honest’ => 'Honest',
        ‘child_qualities_good_friend’ => 'Good friend',
        ‘child_qualities_helpful’ => 'Helpful',
        ‘child_qualities_sense_of_humor’ => 'Sense of humor',
        ‘child_qualities_good_with_hands’ => 'Good with hands-on things',
        ‘child_qualities_gets_along_well’ => 'Gets along well with others',
        ‘child_qualities_independent’ => 'Independent',
        ‘child_qualities_responsible’ => 'Responsible',
        ‘child_qualities_respectful’ => 'Respectful to adults',
        ‘child_qualities_creative’ => 'Creative',
        ‘child_qualities_athletic’ => 'Athletic',
        ‘child_qualities_other’ => 'Other',
        ‘child_concerns_friends_in_trouble’ => 'Friends who get in trouble',
        ‘child_concerns_peer_rejection’ => 'Peer rejection / Getting bullied',
        ‘child_concerns_grades’ => 'Grades',
        ‘child_concerns_not_completing_homework’ => 'Not turning in completed homework',
        ‘child_concerns_moodiness’ => 'Moodiness',
        ‘child_concerns_defiance’ => 'Defiance',
        ‘child_concerns_back_talking’ => 'Back-talking',
        ‘child_concerns_low_motivation’ => 'Low motivation',
        ‘child_concerns_boy_girl_friend_issues’ => 'Boyfriend/Girlfriend issues',
        ‘child_concerns_poor_eating_habits’ => 'Poor eating habits',
        ‘child_concerns_poor_sibling_relationships’ => 'Poor sibling relationships',
        ‘child_concerns_substance_use’ => 'Substance use',
        ‘child_concerns_too_dependent_parent’ => 'Too dependent on parent(s)',
        ‘child_concerns_not_helping_house’ => 'Not helping around the house',
        ‘child_concerns_disorganized’ => 'Disorganized',
        ‘child_concerns_mental_health’ => 'Mental health',
        ‘child_concerns_physical_health’ => 'Physical health',
        ‘child_concerns_not_healthy_choices’ => 'Not making healthy choices',
        ‘child_concerns_too_much_screen_time’ => 'Too much screen time',
        ‘child_concerns_other’ => 'Other',
        ‘child_wellbeing’ => ['Very poor',
                              'Somewhat poor',
                              'Neutral',
                              'Somewhat well',
                              'Very well'],
        ‘family_strengths_enjoy_spending_time’ => 'We enjoy spending time together',
        ‘family_strengths_work_well_team’ => 'We work well together as a team',
        ‘family_strengths_supportive’ => 'We are supportive of each other',
        ‘family_strengths_communicate’ => 'We communicate well',
        ‘family_strengths_sense_of_humor’ => 'We have a great sense of humor',
        ‘family_strengths_have_back’ => 'We have each other’s back',
        ‘family_strengths_have_fun’ => 'Our ability to have fun together',
        ‘family_strengths_cope’ => 'Our ability to cope with challenges',
        ‘family_strengths_concern’ => 'Our care and concern for each other',
        ‘interested_strategies’ => ['Not at all',
                                    'Somewhat interested',
                                    'Neutral',
                                    'Interested',
                                    'Very interested'],
        ‘well_school_relationships’ => 'Peer relationships',
        ‘well_school_grades’ => 'Grades',
        ‘well_school_sports’ => 'Sports',
        ‘well_school_clubs’ => 'Clubs',
        ‘well_school_getting_along_teachers’ => 'Getting along with teachers',
        ‘well_school_attendance’ => 'Attendance',
        ‘well_school_other’ => 'Other',
        ‘well_school_none’ => 'None of the above',
        ‘challenges_school_friends_trouble’ => 'Friends who get in trouble',
        ‘challenges_school_rejection’ => 'Peer rejection / Getting bullied',
        ‘challenges_school_grades’ => 'Grades',
        ‘challenges_school_attendance’ => 'Attendance / Missing school',
        ‘challenges_school_motivation’ => 'Low motivation',
        ‘challenges_school_getting_along_teachers’ => 'Getting along with teachers and other adults',
        ‘challenges_school_homework’ => 'Not turning in completed homework',
        ‘challenges_school_mental_health’ => 'Mental health',
        ‘challenges_school_other’ => 'Other',
        ‘how_school’ => ['Very poorly',
                         'Somewhat poorly',
                         'Acceptable',
                         'Somewhat well',
                         'Very well'],
        ‘loses_temper’ => ['Not true',
                           'Somewhat true',
                           'Certainly true'],
        ‘well_behaved’ => ['Not true',
                           'Somewhat true',
                           'Certainly true'],
        ‘fights_others’ => ['Not true',
                            'Somewhat true',
                            'Certainly true'],
        ‘lies_cheats’ => ['Not true',
                          'Somewhat true',
                          'Certainly true'],
        ‘steals_home’ => ['Not true',
                          'Somewhat true',
                          'Certainly true'],
        ‘use_drugs’ => ['Not true',
                        'Somewhat true',
                        'Certainly true'],
        ‘often_complains’ => ['Not true',
                              'Somewhat true',
                              'Certainly true'],
        ‘many_worries’ => ['Not true',
                           'Somewhat true',
                           'Certainly true'],
        ‘often_unhappy’ => ['Not true',
                            'Somewhat true',
                            'Certainly true'],
        ‘easily_scared’ => ['Not true',
                            'Somewhat true',
                            'Certainly true'],
        ‘friends_behave’ => ['None / Very few',
                             'Some',
                             'Half',
                             'A lot',
                             'All / Almost all'],
        ‘friends_misbehave’ => ['None / Very few',
                                'Some',
                                'Half',
                                'A lot',
                                'All / Almost all'],
        ‘friends_experiment’ => ['None / Very few',
                                 'Some',
                                 'Half',
                                 'A lot',
                                 'All / Almost all'],
        ‘friends_gang’ => ['None / Very few',
                           'Some',
                           'Half',
                           'A lot',
                           'All / Almost all'],
        ‘child_bullied’ => ['Yes',
                            'No',
                            'Don\'t know'],
        ‘child_ebullied’ => ['Yes',
                             'No',
                             'Don\'t know'],
        ‘hard_finishing’ => ['Not true',
                             'A little',
                             'Somewhat',
                             'A lot',
                             'Very true'],
        ‘finish_before’ => ['Not true',
                            'A little',
                            'Somewhat',
                            'A lot',
                            'Very true'],
        ‘difficult_assignments’ => ['Not true',
                                    'A little',
                                    'Somewhat',
                                    'A lot',
                                    'Very true'],
        ‘project_due’ => ['Not true',
                          'A little',
                          'Somewhat',
                          'A lot',
                          'Very true'],
        ‘easy_concentrate’ => ['Not true',
                               'A little',
                               'Somewhat',
                               'A lot',
                               'Very true'],
        ‘keeping_track’ => ['Not true',
                            'A little',
                            'Somewhat',
                            'A lot',
                            'Very true'],
        ‘close_attention’ => ['Not true',
                              'A little',
                              'Somewhat',
                              'A lot',
                              'Very true'],
        ‘stick_goals’ => ['Not true',
                          'A little',
                          'Somewhat',
                          'A lot',
                          'Very true'],
        ‘child_good_job’ => ['Never',
                             'Rarely',
                             'Sometimes',
                             'Often',
                             'Very often'],
        ‘child_reward’ => ['Never',
                           'Rarely',
                           'Sometimes',
                           'Often',
                           'Very often'],
        ‘child_compliment’ => ['Never',
                               'Rarely',
                               'Sometimes',
                               'Often',
                               'Very often'],
        ‘child_praise’ => ['Never',
                           'Rarely',
                           'Sometimes',
                           'Often',
                           'Very often'],
        ‘child_hug’ => ['Never',
                        'Rarely',
                        'Sometimes',
                        'Often',
                        'Very often'],
        ‘child_help’ => ['Never',
                         'Rarely',
                         'Sometimes',
                         'Often',
                         'Very often'],
        ‘free_time’ => ['Never',
                         'Rarely',
                         'Sometimes',
                         'Often',
                         'Very often'],
        ‘hangs_out’ => ['Never',
                         'Rarely',
                         'Sometimes',
                         'Often',
                         'Very often'],
        ‘where_friends’ => ['Never',
                         'Rarely',
                         'Sometimes',
                         'Often',
                         'Very often'],
        ‘after_school’ => ['Never',
                         'Rarely',
                         'Sometimes',
                         'Often',
                         'Very often'],
        ‘when_away’ => ['Never',
                         'Rarely',
                         'Sometimes',
                         'Often',
                         'Very often'],
        ‘coming_day’ => ['Never',
                         'Rarely',
                         'Sometimes',
                         'Often',
                         'Very often'],
        ‘child_activities’ => ['Never',
                         'Rarely',
                         'Sometimes',
                         'Often',
                         'Very often'],
        ‘unsupervised_often’ => ['Never',
                         'Rarely',
                         'Sometimes',
                         'Often',
                         'Very often'],
        ‘on_time’ => ['Never',
                         'Rarely',
                         'Sometimes',
                         'Often',
                         'Very often'],
        ‘check_needs’ => ['Never',
                         'Rarely',
                         'Sometimes',
                         'Often',
                         'Very often'],
        ‘check_homework’ => ['Never',
                         'Rarely',
                         'Sometimes',
                         'Often',
                         'Very often'],
        ‘check_day’ => ['Never',
                        'Rarely',
                        'Sometimes',
                        'Often',
                        'Very often'],
        ‘speak_calmly’ => ['Never',
                           'Rarely',
                           'Sometimes',
                           'Often',
                           'Very often'],
        ‘stick_rules’ => ['Never',
                         'Rarely',
                         'Sometimes',
                         'Often',
                         'Very often'],
        ‘explain_simple’ => ['Never',
                             'Rarely',
                             'Sometimes',
                             'Often',
                             'Very often'],
        ‘dont_like’ => ['Never',
                        'Rarely',
                        'Sometimes',
                        'Often',
                        'Very often'],
        ‘expected_behavior’ => ['Never',
                                'Rarely',
                                'Sometimes',
                                'Often',
                                'Very often'],
        ‘enforce_behavior’ => ['Never',
                               'Rarely',
                               'Sometimes',
                               'Often',
                               'Very often'],
        ‘follow_rules’ => ['Never',
                           'Rarely',
                           'Sometimes',
                           'Often',
                           'Very often'],
        ‘talk_teachers’ => ['Never',
                            'Rarely',
                            'Sometimes',
                            'Often',
                            'Very often'],
        ‘special_visit’ => ['Never',
                           'Rarely',
                           'Sometimes',
                           'Often',
                           'Very often'],
        ‘open_house’ => ['Never',
                         'Rarely',
                         'Sometimes',
                         'Often',
                         'Very often'],
        ‘wecome_visit’ => ['Not true',
                           'Rarely',
                           'Sometimes',
                           'True most of the time',
                           'Always true / Very true'],
        ‘enjoy_teachers’ => ['Not true',
                             'Rarely',
                             'Sometimes',
                             'True most of the time',
                             'Always true / Very true'],
        ‘teachers_care’ => ['Not true',
                            'Rarely',
                            'Sometimes',
                            'True most of the time',
                            'Always true / Very true'],
        ‘teachers_know’ => ['Not true',
                            'Rarely',
                            'Sometimes',
                            'True most of the time',
                            'Always true / Very true'],
        ‘who_friends’ => ['Not confident at all',
                          'Not very confident',
                          'Somewhat confident',
                          'Confident',
                          'Very confident'],
        ‘limit_negative’ => ['Not confident at all',
                             'Not very confident',
                             'Somewhat confident',
                             'Confident',
                             'Very confident'],
        ‘positive_behavior’ => ['Not confident at all',
                                'Not very confident',
                                'Somewhat confident',
                                'Confident',
                                'Very confident'],
        ‘fun_activity’ => ['Not confident at all',
                           'Not very confident',
                           'Somewhat confident',
                           'Confident',
                           'Very confident'],
        ‘homework_on_time’ => ['Not confident at all',
                               'Not very confident',
                               'Somewhat confident',
                               'Confident',
                               'Very confident'],
        ‘child_refusing’ => ['Not confident at all',
                             'Not very confident',
                             'Somewhat confident',
                             'Confident',
                             'Very confident'],
        ‘child_get_way’ => ['Not confident at all',
                            'Not very confident',
                            'Somewhat confident',
                            'Confident',
                            'Very confident'],
        ‘argue_rules’ => ['Not confident at all',
                          'Not very confident',
                          'Somewhat confident',
                          'Confident',
                          'Very confident'],
        ‘down_depressed’ => ['Not confident at all',
                             'Not very confident',
                             'Somewhat confident',
                             'Confident',
                             'Very confident'],
        ‘mood_swings’ => ['Not confident at all',
                          'Not very confident',
                          'Somewhat confident',
                          'Confident',
                          'Very confident'],
        ‘got_angry’ => ['Never',
                        'Rarely',
                        'Sometimes',
                        'Often',
                        'Very often'],
        ‘got_way’ => ['Never',
                      'Rarely',
                      'Sometimes',
                      'Often',
                      'Very often'],
        ‘stress_interactions’ => ['No stress',
                                  'A little stress',
                                  'Somewhat stressful',
                                  'A lot of stress',
                                  'Very high stress'],
        ‘current_stress’ => ['No stress',
                             'A little stress',
                             'Somewhat stressful',
                             'A lot of stress',
                             'Very high stress'],
        ‘you_problem’ => ['No',
                          'Yes, currently',
                          'Yes, in the past'],
        ‘little_pleasure’ => ['Not at all',
                              'Several days',
                              'More than half the days',
                              'Nearly every day'],
        ‘down_hopeless’ => ['Not at all',
                            'Several days',
                            'More than half the days',
                            'Nearly every day'],
        ‘religious_community’ => ['Not at all',
                                  'Once or more'],
        ‘psych’ => ['Not at all',
                    'Once or more'],
        ‘spouse’ => ['Not at all',
                     'Once or more'],
        ‘friend_coworker’ => ['Not at all',
                              'Once or more'],
        ‘relative’ => ['Not at all',
                       'Once or more'],
        ‘coach’ => ['Not at all',
                    'Once or more'],
        ‘nurse’ => ['Not at all',
                    'Once or more'],
        ‘caregiver_support’ => ['Not at all',
                                'Once or more']
    ];

    public static function get($field, $index = null)
    {
        if($index){
            return self::getRadioValue($field, $index);
        }

        return self::$fields[$name];
    }

    public static function getRadioValue($field, $index)
    {
        return self::$fields[$name][$index];
    }
}
